### ISSUE TITLE
流水线的凭据是否可以细化下

### ISSUE THREAD

**Issue by zgfh** [DaoCloud/DaoCloud-docs#1023]
**Describe the bug**
如下图，只说明了需要用github或gitlab 的token，但如何创建，需要什么权限都没有说明，建议优化
![image](https://user-images.githubusercontent.com/11729624/224908419-fe44f5b0-e2e9-44c4-9908-b767f14f9d19.png)

**Comment by windsonsea** [comment]
https://docs.daocloud.io/amamba/user-guide/pipeline/credential.html

cc @Michelle951
