### ISSUE TITLE
【讨论】【创建流程】是否添加一级步骤

### ISSUE THREAD

**Issue by yanrongshi** [DaoCloud/DaoCloud-docs#114]
**当前的创建步骤上下感觉不连贯，建议在当前的创建步骤外添加一个【大步骤】的抽象层，使文档更易读。**
### 当前的
![image](https://user-images.githubusercontent.com/29862632/190417901-c653b4d3-bd67-4c3d-9007-bfea4aff2916.png)
![image](https://user-images.githubusercontent.com/29862632/190417973-729cae44-b12a-4aa0-866e-60b89b940620.png)
### 建议的
<img width="902" alt="image" src="https://user-images.githubusercontent.com/29862632/190418351-a782b173-4273-4e92-ad5f-717d41ab1e58.png">

### 友商的
**阿里**
![image](https://user-images.githubusercontent.com/29862632/190419292-5431146c-0b3c-48ca-90e1-3ba2d666dc85.png)
**华为**：看着很乱
![image](https://user-images.githubusercontent.com/29862632/190418705-5b0c1c69-c91a-4614-bdef-6e9e47eef479.png)
### 这样做的理由
- 区分友商
- 上下文衔接更加连贯

**Comment by windsonsea** [comment]
Closed by PR #115
