### ISSUE TITLE
可观测性-资源监控-容器监控-前提条件中没加入参考链接

### ISSUE THREAD

**Issue by ihuibin** [DaoCloud/DaoCloud-docs#1473]
可观测性-资源监控-容器监控-前提条件中没加入参考链接
![WX20230509-182857@2x](https://github.com/DaoCloud/DaoCloud-docs/assets/18320100/4b2abfa6-21d7-43ea-9ea8-7902899ec9a0)

**Comment by Michelle951** [comment]
fixed by pull request: https://github.com/DaoCloud/DaoCloud-docs/pull/1893

**Comment by Michelle951** [comment]
fixed by pull request: https://github.com/DaoCloud/DaoCloud-docs/pull/1893
