### ISSUE TITLE
安装器安装时 minio 和 mysql pod无法启动，健康检查有问题

### ISSUE THREAD

**Issue by HenrrryLiu** [DaoCloud/DaoCloud-docs#1866]
在线安装和离线安装过程中，使用nodeport方式暴露平台
安装器安装过程中停留在Task6 
![image](https://github.com/DaoCloud/DaoCloud-docs/assets/91894331/47b4f113-c90c-49ff-9a30-dd872d3fa8ee)

日志显示等待mysql
![image](https://github.com/DaoCloud/DaoCloud-docs/assets/91894331/c7790035-d5cc-49a5-9cf8-24d2125a99f2)

根据安装日志提示，查看mcamel-common-mysql-cluster-mysql-0的日志
![image](https://github.com/DaoCloud/DaoCloud-docs/assets/91894331/c051533d-c248-4943-aa05-07d86addd28f)

同时查看pod，mcamel-system ns中 minio mysql 相关的pod 无法启动
![image](https://github.com/DaoCloud/DaoCloud-docs/assets/91894331/bce6d821-d727-42c1-8e6e-f7cfd6c44124)

查看相应pod，事件均为健康检查出问题
![image](https://github.com/DaoCloud/DaoCloud-docs/assets/91894331/6ad14140-6e72-4b04-b633-79be7e129dfb)

![image](https://github.com/DaoCloud/DaoCloud-docs/assets/91894331/c10aee1d-c3b1-4960-914a-aa286088e775)

![image](https://github.com/DaoCloud/DaoCloud-docs/assets/91894331/d95d6eaa-235d-4be2-bfdf-bc1fa683e0e2)

有没有大佬帮忙看看哈？
万分感谢！

**Comment by HenrrryLiu** [comment]
哈喽～
使用的在线安装模式
版本是0.8.0
`export VERSION=v0.8.0 `
安装时使用 NodePort 暴露控制台，没用config文件
`./dce5-installer install-app -z`

**Comment by Penguin-zlh** [comment]
可以先尝试一下该命令：
`kubectl exec mcamel-common-mysql-cluster-mysql-0 -n mcamel-system -c mysql -- mysql --defaults-file=/etc/mysql/client.conf -NB -e 'update sys_operator.status set value="1"  WHERE name="configured"'
kubectl exec mcamel-common-kpanda-mysql-cluster-mysql-0 -n mcamel-system -c mysql -- mysql --defaults-file=/etc/mysql/client.conf -NB -e 'update sys_operator.status set value="1"  WHERE name="configured"'
`

参考文档：https://docs.daocloud.io/middleware/mysql/faq/faq-pod/#pod-running-34
