### ISSUE TITLE
ES集群容量规划，快速计算 工时（错别字，应该为 公式？）

### ISSUE THREAD

**Issue by liyuerich** [DaoCloud/DaoCloud-docs#1869]
ES集群容量规划，快速计算工时（错别字，应该为 公式？）

<img width="1315" alt="image" src="https://github.com/DaoCloud/DaoCloud-docs/assets/97269208/1815c511-4fdb-4392-92cb-abed8428e5cd">

**Comment by Michelle951** [comment]
fixed by pull request: https://github.com/DaoCloud/DaoCloud-docs/pull/1893
