### ISSUE TITLE
安装velero插件无需提前配置密钥，如果配置了，会失败

### ISSUE THREAD

**Issue by liyuerich** [DaoCloud/DaoCloud-docs#1965]
https://docs.daocloud.io/kpanda/user-guide/backup/install-velero

![image](https://github.com/DaoCloud/DaoCloud-docs/assets/97269208/5204bb0a-4e16-418f-a79c-631189ee1f7b)

如果安装密钥，velero 插件安装的时候会失败，报错：

helm upgrade --create-namespace=true --install=true --namespace=velero --values=/home/shell/helm/values-velero-3.0.0.yaml --version=3.0.0 velero /home/shell/helm/velero-3.0.0.tgz --kube-as-user=kpanda-addon-liyuecluster3node
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/.kube/config
Release "velero" does not exist. Installing it now.
Error: rendered manifests contain a resource that already exists. Unable to continue with install: Secret "velero-s3-credential" in namespace "velero" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "velero"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "velero"

**Comment by yanrongshi** [comment]
Fix：https://github.com/DaoCloud/DaoCloud-docs/pull/1968
