### ISSUE TITLE
部份页面中英文内容无法对应

### ISSUE THREAD

**Issue by xfanwu** [DaoCloud/DaoCloud-docs#2029]
**Describe the bug**
部份页面中英文版本内容无法对应

**To Reproduce**
例如：
https://docs.daocloud.io/download/dce5/
https://docs.daocloud.io/en/download/dce5/

例如：
https://docs.daocloud.io/kpanda/user-guide/clusters/create-cluster/
https://docs.daocloud.io/en/kpanda/user-guide/clusters/create-cluster/

**Comment by windsonsea** [comment]
目前 download, install, release notes 都已全部同步，参见：

https://docs.daocloud.io/en/download/
https://docs.daocloud.io/en/install/
https://docs.daocloud.io/en/dce/dce-rn/230630/

For kpanda pages, cc @Michelle951

**Comment by Michelle951** [comment]
fixed by pull request: https://github.com/DaoCloud/DaoCloud-docs/pull/2069
