### ISSUE TITLE
文档中某些功能描述词汇不统一

### ISSUE THREAD

**Issue by xfanwu** [DaoCloud/DaoCloud-docs#2030]
**Describe the bug**
功能描述词汇不统一，部份文档中出现的「功能描述」无法与产品自身匹配，例如「接入集群」，英文同时出现了「join cluster」、「connect to cluster」，实际上产品按钮显示为「integrate cluster」

**To Reproduce**
例如：
https://docs.daocloud.io/en/kpanda/user-guide/clusters/integrate-cluster/

**Comment by windsonsea** [comment]
@Michelle951

**Comment by Michelle951** [comment]
Fixed by pull request https://github.com/DaoCloud/DaoCloud-docs/pull/2062
