### ISSUE TITLE
License申请流程无英文版本

### ISSUE THREAD

**Issue by xfanwu** [DaoCloud/DaoCloud-docs#2031]
**Describe the bug**
License 申请流程无英文版本

**To Reproduce**
1. https://docs.daocloud.io/en/trial/#2nd-apply-for-a-license-key
2. https://qingflow.com/f/58604bf8

**Comment by windsonsea** [comment]
是的，这个暂时还没法解决，因为轻流只有中文版。

@lemontrees123

**Comment by windsonsea** [comment]
已新增 双语版本图片：

https://docs.daocloud.io/en/dce/license0.html
