### ISSUE TITLE
Some wrong links

### ISSUE THREAD

**Issue by yanrongshi** [DaoCloud/DaoCloud-docs#2053]
![image](https://github.com/DaoCloud/DaoCloud-docs/assets/29862632/ac6ace7d-f39e-40bd-a68a-bfbe99ab8bbc)

![image](https://github.com/DaoCloud/DaoCloud-docs/assets/29862632/fbc62df9-b8e7-4a71-b56c-61e0a8171cf0)

**Comment by windsonsea** [comment]
Noted. Will fix it soon.
