### ISSUE TITLE
Update Ghippo 0.8.0, 0.9.0, 0.10.0 release note

### ISSUE THREAD

**Issue by yitingdc** [DaoCloud/DaoCloud-docs#207]
Please update Ghippo 0.8.0, 0.9.0, 0.10.0 release note, referring to :
https://gitlab.daocloud.cn/ndx/ghippo/-/blob/master/release-notes/notes/v0.10.0/audit-arm-license-ldap-authz-https.yaml

https://ndx.gitpages.daocloud.io/ghippo/zh/00Bulletin/v0.9.html

https://ndx.gitpages.daocloud.io/ghippo/zh/00Bulletin/v0.8.html

**Comment by yitingdc** [comment]
@windsonsea

**Comment by windsonsea** [comment]
noted, on the way.
