### ISSUE TITLE
安装 insight-agent  文档描述不清楚

### ISSUE THREAD

**Issue by zgfh** [DaoCloud/DaoCloud-docs#238]
**Describe the bug**

![image](https://user-images.githubusercontent.com/11729624/195297787-ef914761-4851-4958-8590-5bcfd7a8115e.png)
如上图，不知道怎么获取这些参数，以及应该修改哪些参数

**Comment by windsonsea** [comment]
@justedennnnn

**Comment by justedennnnn** [comment]
会尽快修改文档，优化可读性
