### ISSUE TITLE
故障排查部分 ： 登录报错401 或403 部分内容 不准确

### ISSUE THREAD

**Issue by liyuerich** [DaoCloud/DaoCloud-docs#243]
我的环境出现了这个错误：登录无限循环，报错 401 或 403， 按照文档进行排查

1 查看 RequestAuthentication ghippo CR。
确保 JWT 令牌中的 iss 字段包含在 RequestAuthentication ghippo CR 中。- 这个和黑色图片中红色框中的信息是对应关系吗？
![image](https://user-images.githubusercontent.com/97269208/195547850-fde2f919-ee4c-4a73-9c67-8d2d4392b492.png)

2 紫色部分的信息是怎么出来的？

![image](https://user-images.githubusercontent.com/97269208/195546675-948c6bef-02e4-4f2d-bb0c-cfcefce6529c.png)
3 更换了 keycloak 数据库，导致 isito gateway 的 authn 模块的 jwks 公钥可能错了
在哪里看到是否错了？ 还是说直接重启即可？
这种情况需要重启 istiod

4 如果任意一个 jwtRules.jwksUri 地址访问不通，请尝试解决为什么访问不通这个问题
下面没有尝试解决方法或者提示

5 进入到一个有 curl 或者 wget 命令的容器。

这个命令中没有namespace，执行的时候报错
kubectl exec -it ghippo-anakin-cd6859496-flf9j sh

6 使用 curl 或者 wget 命令访问 jwtRules.jwksUri 的地址
命令和显示的结果写在了一起，看上去会混淆

![image](https://user-images.githubusercontent.com/97269208/195580928-9d8bcaa4-8ca3-4cd0-9be4-7e37994f54f8.png)

**Comment by windsonsea** [comment]
@lemontrees123

**Comment by SAMZONG** [comment]
test for issue bot

**Comment by windsonsea** [comment]
@yitingdc

**Comment by windsonsea** [comment]
The doc link is:

https://docs.daocloud.io/reference/troubleshooting/ghippo02/
