### ISSUE TITLE
在文档站上搜索某关键字回车，提示来到未知空间

### ISSUE THREAD

**Issue by liyuerich** [DaoCloud/DaoCloud-docs#244]
在文档站上输入insight关键字，然后回车：

![企业微信截图_cbab253d-ee9d-4193-8684-53427d3fee6a](https://user-images.githubusercontent.com/97269208/195584960-be4bd5fe-7bf6-4f11-8554-b979a14f4a26.png)

![企业微信截图_6a18ec16-c777-4a5b-9d4a-3cf92a4559dc](https://user-images.githubusercontent.com/97269208/195584962-7035cdf4-f2d3-4f95-b30c-49ada15c59fe.png)

**Comment by SAMZONG** [comment]
#248
