### ISSUE TITLE
通过yaml创建Deployment部署策略配置 在新版本中失效，建议更新

### ISSUE THREAD

**Issue by ying62506799** [DaoCloud/DaoCloud-docs#2532]
![Uploading image.png…]()
需要将上诉配置修改如下
affinityName: default
clusternames:
- bztest001
- olm-cluster-test

**Comment by windsonsea** [comment]
图片好像上传失败了，那个截图还能找到吗

**Comment by windsonsea** [comment]
非常感谢 @ying62506799

多云创建 deployment 页面： https://docs.daocloud.io/kairship/workload/yaml.html

yaml 代码需要更新了

@samzong @wlp1153468871
