### ISSUE TITLE
【多云编排】目前karmada的版本是v1.6.0，需要更新karmada的版本

### ISSUE THREAD

**Issue by yt-huang** [DaoCloud/DaoCloud-docs#2665]
原文信息如下：
#####
1、Karmada 的版本是多少？能否指定版本？是否可以升级？

当前默认版本 v1.4.0，支持用户自主升级。

######
url地址如下：
https://docs.daocloud.io/kairship/intro/faq.html

**Comment by ying62506799** [comment]
![图1](https://github.com/DaoCloud/DaoCloud-docs/assets/33514158/96854148-a842-459d-b64f-7069e10a8d45)
![图2](https://github.com/DaoCloud/DaoCloud-docs/assets/33514158/eaa921a5-b0cd-4ae1-93a4-21ee0d63f671)
包括如下的截图也需要一并修改
