### ISSUE TITLE
语句错误

### ISSUE THREAD

**Issue by ying62506799** [DaoCloud/DaoCloud-docs#2666]
1、"来自"和"于"重复，属于成分赘余语病。“成分赘余”的主要特征是用词语义重复。“来自”表示“来源于”。而“于”字的词义之中本身也有自，从的意思，所以说，这里出现了语义重复。（百度百科）
![图3](https://github.com/DaoCloud/DaoCloud-docs/assets/33514158/7c6bb861-5e76-4a5d-bbaf-b68d9bc9fd23)
2】url地址：
https://docs.daocloud.io/kairship/instance/add.html

**Comment by windsonsea** [comment]
谢谢提醒🙏  will fix soon
