### ISSUE TITLE
【容器管理】语句错误

### ISSUE THREAD

**Issue by ying62506799** [DaoCloud/DaoCloud-docs#2690]
<img width="1148" alt="集群巡检" src="https://github.com/DaoCloud/DaoCloud-docs/assets/33514158/a7ba6901-e07d-4c08-b6fe-382ea9808b44">
应该将‘解决xxxx的困境’ 改为‘摆脱xxxx的困境’更合理
url地址：https://docs.daocloud.io/kpanda/user-guide/inspect/index.html

**Comment by windsonsea** [comment]
Hi @ying62506799 , would you like to raise a PR if the solution is clear 😄
