### ISSUE TITLE
make serve 出错

### ISSUE THREAD

**Issue by yitingdc** [DaoCloud/DaoCloud-docs#271]
**Describe the bug**
文档站仓库在开发环境跑起来的readme步骤是否有遗漏? 
<img width="435" alt="image" src="https://user-images.githubusercontent.com/59356937/196828934-333aaff0-2997-492f-b4e0-e918f2c13e09.png">

或者 docs/zh/mkdocs.yml 里列的 print-site 有用吗?

**To Reproduce**
mac电脑, 按readme步骤clone好仓库, 
启动docker
make serve
出错:
<img width="648" alt="image" src="https://user-images.githubusercontent.com/59356937/196828143-f756f953-d602-4551-9ca0-744b780e7e7d.png">

我最后用注释掉print-site解决了这个问题, 但是
readme有没有漏掉什么步骤?

**Comment by SAMZONG** [comment]
收到问题，预计会在今天修复 😊
