### ISSUE TITLE
【可观测性】dce4安装insight-agent还需要加一个问题项，DCE4有默认超卖策略，安装时需要将insight-system下的超卖策略删除

### ISSUE THREAD

**Issue by Penguin-zlh** [DaoCloud/DaoCloud-docs#2749]
**描述**
dce4安装insight-agent还需要加一个问题项，DCE4有默认超卖策略，安装时需要将insight-system下的超卖策略删除

文档地址：https://docs.daocloud.io/insight/quickstart/other/install-agentindce.html

**预期**
路径：「设置」-「空间管理」-「insight-system」-「超卖策略」

这是删除insight-system这个namespace下超卖策略的截图：
<img width="1436" alt="image" src="https://github.com/DaoCloud/DaoCloud-docs/assets/57695165/277a02cb-4c7d-46cb-b3f9-c786a3f238c3">

**Comment by windsonsea** [comment]
@justedennnnn @JaredTan95

**Comment by JaredTan95** [comment]
> @justedennnnn @JaredTan95

ok
