### ISSUE TITLE
【中间件】【MySQL-快速入门】缺少实例监控、配置参数、备份管理功能的介绍

### ISSUE THREAD

**Issue by fangbin9527** [DaoCloud/DaoCloud-docs#2787]
文档地址：https://docs.daocloud.io/middleware/mysql/user-guide/logs.html#_1
文档：
![image](https://github.com/DaoCloud/DaoCloud-docs/assets/71134088/644437f1-4d39-442b-8fa1-892a6367cecb)

最新版本：![image](https://github.com/DaoCloud/DaoCloud-docs/assets/71134088/09018e6c-5812-41ee-8f6b-021b711ec2c1)

**Comment by ModetaNiu** [comment]
![image](https://github.com/user-attachments/assets/6cf0fe2b-a7be-47b7-a41b-a2612eecf1d3)
the current page

**Comment by ModetaNiu** [comment]
Seems fixed: https://docs.daocloud.io/middleware/mysql/user-guide/view/
