### ISSUE TITLE
【中间件】【MongoDB】Mongodb数据库-快速入门文档中有把mongodb文字错误（英文文档需要同步修改）

### ISSUE THREAD

**Issue by fangbin-Li** [DaoCloud/DaoCloud-docs#2791]
问题1：
![image](https://github.com/DaoCloud/DaoCloud-docs/assets/71134088/885c7df1-cfb2-4d85-b207-ab62c25386c5)
问题2：
![image](https://github.com/DaoCloud/DaoCloud-docs/assets/71134088/55bb880b-a5bd-4201-81c0-cc4dbd8e4429)

问题3：对于用户来说，用户不知道“Insight ”是做什么的，建议增加截图提示
![image](https://github.com/DaoCloud/DaoCloud-docs/assets/71134088/24424809-8b51-404c-99f7-5471a8da259b)

![image](https://github.com/DaoCloud/DaoCloud-docs/assets/71134088/ff9923e6-dd58-44b5-b5fa-54d7f23f9a37)

**Comment by Fan-Lin** [comment]
@windsonsea  The content has been modified  
https://docs.daocloud.io/download/modules/middleware/mongodb.html?h=mon
