### ISSUE TITLE
【中间件】-【PostgreSQL】“手工设置工作负载反亲和”中的图片显示不清晰

### ISSUE THREAD

**Issue by fangbin9527** [DaoCloud/DaoCloud-docs#2792]
https://docs.daocloud.io/middleware/postgresql/user-guide/antiaffinity.html
![image](https://github.com/DaoCloud/DaoCloud-docs/assets/71134088/c93840ae-5911-440e-8208-f2ed4d49c110)
![image](https://github.com/DaoCloud/DaoCloud-docs/assets/71134088/74a7d3ac-0149-423d-bdda-755db3deda11)

**Comment by ModetaNiu** [comment]
Already fixed. See https://docs.daocloud.io/middleware/postgresql/user-guide/antiaffinity.html
