### ISSUE TITLE
【中间件】【Redis】--【快速入门】功能需要优化图片和文字信息

### ISSUE THREAD

**Issue by fangbin9527** [DaoCloud/DaoCloud-docs#2793]
一、部署类型为“主备模式”需要修改为"哨兵模式”
![image](https://github.com/DaoCloud/DaoCloud-docs/assets/71134088/52afb3e5-86ec-407b-9dba-dca4b13eddb7)
![image](https://github.com/DaoCloud/DaoCloud-docs/assets/71134088/26983667-0304-4899-bc94-7d322348c74f)
缺少：LoadBalancer
![image](https://github.com/DaoCloud/DaoCloud-docs/assets/71134088/fa85fb6b-7b56-47e6-a87f-6654e981b7c6)
![image](https://github.com/DaoCloud/DaoCloud-docs/assets/71134088/348280bd-ff95-4b00-9d41-10965a71d093)
![image](https://github.com/DaoCloud/DaoCloud-docs/assets/71134088/41d9758c-df0f-4430-ba4c-eea9062dd8ad)
缺少：LoadBalancer
![image](https://github.com/DaoCloud/DaoCloud-docs/assets/71134088/e58f47d8-1f27-432a-8130-912fd60cc578)
![image](https://github.com/DaoCloud/DaoCloud-docs/assets/71134088/5a5f1f5b-ea0d-4d54-b458-edede2606981)
![image](https://github.com/DaoCloud/DaoCloud-docs/assets/71134088/4aa3e992-1d3f-4eb0-905b-271372efe189)

问题：对于用户来说，用户不知道“Insight ”是做什么的，建议增加截图提示
![image](https://github.com/DaoCloud/DaoCloud-docs/assets/71134088/4f6e547b-61a8-44d6-a434-48fc2395f78a)

**Comment by ModetaNiu** [comment]
Already fixed, see the current page: https://docs.daocloud.io/middleware/redis/user-guide/create/
