### ISSUE TITLE
【镜像仓库】release notes 超过3个月未更新

### ISSUE THREAD

**Issue by ying62506799** [DaoCloud/DaoCloud-docs#2805]
<img width="669" alt="未更新" src="https://github.com/DaoCloud/DaoCloud-docs/assets/33514158/d6f5f8b6-0425-45d6-b445-d0c92c5bf1fa">

**Comment by lengrongfu** [comment]
<img width="652" alt="image" src="https://github.com/DaoCloud/DaoCloud-docs/assets/15009201/3f070375-cef9-43f5-a636-5dbd8dc2408a">
目前已经更新。

**Comment by Fan-Lin** [comment]
fixed #3493
