### ISSUE TITLE
【微服务引擎】服务接入[自动管理]

### ISSUE THREAD

**Issue by zhh1234567** [DaoCloud/DaoCloud-docs#2818]
## 概述
bug 概述
在自动管理中，策略配置应为"修改策略配置"，缺少"自定义健康检查接口"，目标服务无连接信息
## 环境信息
https://docs.daocloud.io/skoala/gateway/service/auto-manage/#_4
## 复现几率
必现(100%)

## 重现步骤

![image](https://github.com/DaoCloud/DaoCloud-docs/assets/119397418/f2c74855-7831-4783-a55a-5653c74c586c)

**Comment by zhh1234567** [comment]
应补充对应的：自定义健康检查接口

**Comment by windsonsea** [comment]
Seems this issue has been fixed.
See the current online page: https://docs.daocloud.io/skoala/gateway/service/auto-manage/#_3
