### ISSUE TITLE
“保姆式安装社区版”安装命令有误

### ISSUE THREAD

**Issue by FloatXD** [DaoCloud/DaoCloud-docs#2861]
https://docs.daocloud.io/blogs/230405-step-by-step-dce5.html#_5
![图片](https://github.com/DaoCloud/DaoCloud-docs/assets/76234281/8315b428-559c-4cd2-8bf0-5c2ce0aef44a)

执行安装中的./dce5-installer install-app -z -k 应改为./dce5-installer install-app -z

**Comment by jzhupup** [comment]
已更改
