### ISSUE TITLE
【安装商业版】执行离线安装依赖项命令错误

### ISSUE THREAD

**Issue by FloatXD** [DaoCloud/DaoCloud-docs#2865]
![图片](https://github.com/DaoCloud/DaoCloud-docs/assets/76234281/2b3db89e-6139-441b-b44b-610d12bca8a5)
./install_prerequisite_${VERSION}.sh offline full

**Comment by jzhupup** [comment]
应该是地址有问题，之前就更新了
![image](https://github.com/DaoCloud/DaoCloud-docs/assets/89386022/ae5727bc-c966-4e01-818d-c75142d70803)
