### ISSUE TITLE
[可观测性]Instrumentation CR在insight v0.22.0之后与服务网格产品串联场景下如何修改CR

### ISSUE THREAD

**Issue by tukwila** [DaoCloud/DaoCloud-docs#2888]
**Describe the bug**

https://docs.daocloud.io/insight/quickstart/otel/operator.html#instrumentation-cr

![image](https://github.com/DaoCloud/DaoCloud-docs/assets/13757056/bd0c8d29-0c0e-4045-9cbd-972f8a1b3b58)

从insight v0.22.0版本开始不需要用户手动安装 Instrumentation CR，但是与服务网格产品链路串联场景下如何配置？希望有单独详细的说明

**Comment by JaredTan95** [comment]
需要手动在 "自定义资源"中 更新这个 CR。我更新一下 文档。
