### ISSUE TITLE
【virtnest】yaml示例问题

### ISSUE THREAD

**Issue by sangy001** [DaoCloud/DaoCloud-docs#2963]
https://docs.daocloud.io/virtnest/quick-start/create-image/#yaml

![image](https://github.com/DaoCloud/DaoCloud-docs/assets/37102834/fec8a52f-472d-4242-8b1d-1b49721af776)

描述应该为“点击查看创建虚机的yaml示例”

**Comment by Fan-Lin** [comment]
fixed #2985
