### ISSUE TITLE
【容器管理】英文模式下，缺少“全局集群工作节点扩容”文档

### ISSUE THREAD

**Issue by shijinye** [DaoCloud/DaoCloud-docs#3075]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
![image](https://github.com/DaoCloud/DaoCloud-docs/assets/36811869/65bbfbdd-4b2a-4aa5-83e0-813ad3999470)
![image](https://github.com/DaoCloud/DaoCloud-docs/assets/36811869/2cceb7f4-652e-4d44-bd20-8d21dc29f378)

目前中文模式下存在该篇文档的使用，但是英文模式下，没有

**Describe alternatives you've considered**

**Additional context**

**Comment by Fan-Lin** [comment]
文档存在，只是跳转有问题：https://docs.daocloud.io/en/kpanda/best-practice/add-worker-node-on-global.html#_3
