### ISSUE TITLE
【hwameistor】“验证 LocalDiskClaim 对象” 结果需要更新

### ISSUE THREAD

**Issue by FloatXD** [DaoCloud/DaoCloud-docs#3093]
https://docs.daocloud.io/storage/hwameistor/resources/storagepool/#localdiskclaim
![图片](https://github.com/DaoCloud/DaoCloud-docs/assets/76234281/1e3342a7-2558-478f-a047-9c6dfeac887a)
LDC资源在bound后会自动删除

**Comment by windsonsea** [comment]
红框内容改为：

```
LocalDiskClaim 对象在挂载（bound）后会被自动删除，你可以运行以下命令查看其是否删除：
```console
# kubectl get ldc
No resources found
```
```
