### ISSUE TITLE
[kant][zh+en]管理边缘单元-边缘单元状态设定与现有的不一致

### ISSUE THREAD

**Issue by wlq1212** [DaoCloud/DaoCloud-docs#3105]
![image](https://github.com/DaoCloud/DaoCloud-docs/assets/95007522/746a2590-f4ba-4f24-8999-9e3ca7823bdd)

**Comment by zhiyingfang2022** [comment]
边缘状态已更新：https://docs.daocloud.io/kant/user-guide/edge-unit/manage-unit/
