### ISSUE TITLE
【镜像仓库】【中英文】镜像列表缺少对镜像删除的介绍

### ISSUE THREAD

**Issue by yt-huang** [DaoCloud/DaoCloud-docs#3117]
镜像列表中缺少对镜像删除功能的介绍
1、需要编写 针对公有以及私有镜像空间删除镜像的前提
2、需要填充截图
<img width="1004" alt="image" src="https://github.com/DaoCloud/DaoCloud-docs/assets/33514158/79e76077-2f02-48a3-b5e3-df88a2f31e34">

1、镜像删除
<img width="1188" alt="image" src="https://github.com/DaoCloud/DaoCloud-docs/assets/33514158/3f461fac-423a-4a65-b899-5c28052fcd69">
2、版本删除
<img width="1238" alt="image" src="https://github.com/DaoCloud/DaoCloud-docs/assets/33514158/bf885251-fb40-4c20-9c68-8116d8e14e87">
<img width="1222" alt="image" src="https://github.com/DaoCloud/DaoCloud-docs/assets/33514158/58e56860-a913-4042-9240-0ac45f350733">

**Comment by ModetaNiu** [comment]
Seems fixed, thanks~
See the current page: https://docs.daocloud.io/kangaroo/space/imagelist/
