### ISSUE TITLE
【多云编排】多云实例信息展示的图已经过期， 需要更新

### ISSUE THREAD

**Issue by liyuerich** [DaoCloud/DaoCloud-docs#3118]
**Describe the bug**
多云实例信息展示的图已经过期， 需要更新

https://docs.daocloud.io/kairship/instance/

<img width="1414" alt="image" src="https://github.com/DaoCloud/DaoCloud-docs/assets/97269208/5c6b6f8a-e2f0-431a-9be4-8a7084418d14">

**Comment by wlp1153468871** [comment]
已经修复，现在的文档：https://docs.daocloud.io/kairship/instance/
