### ISSUE TITLE
【ghippo】【en】建议将”Access Control“改为”Users and Access Control“

### ISSUE THREAD

**Issue by wlq1212** [DaoCloud/DaoCloud-docs#3121]
![image](https://github.com/DaoCloud/DaoCloud-docs/assets/95007522/ab541273-2637-4072-8c17-1d85cd0377c5)

**Comment by windsonsea** [comment]
这个没必要改，英文文档要跟 UI 保持一致：

<img width="1428" alt="image" src="https://github.com/DaoCloud/DaoCloud-docs/assets/79828097/a08cae33-bc90-4044-bfd1-3afa04c081e4">

**Comment by windsonsea** [comment]
This will be closed. Thanks for your contribution.
