### ISSUE TITLE
【多云编排】常见问题-当前支持转换哪些 Kubernetes 资源？ 描述不准确

### ISSUE THREAD

**Issue by liyuerich** [DaoCloud/DaoCloud-docs#3175]
**Describe the bug**

https://docs.daocloud.io/kairship/workload/promote/

常见问题-当前支持转换哪些 Kubernetes 资源？ 描述不准确

现在服务和路由也支持转换

<img width="1353" alt="image" src="https://github.com/DaoCloud/DaoCloud-docs/assets/97269208/376e02ed-d940-4c45-91e3-f35f6cb4af1c">

**Comment by ModetaNiu** [comment]
https://docs.daocloud.io/kairship/workload/promote/ 
Seems fixed.
