### ISSUE TITLE
【ghippo】【zh+en】需添加运营管理创建过程

### ISSUE THREAD

**Issue by wlq1212** [DaoCloud/DaoCloud-docs#3186]
![企业微信截图_6ad06e13-7e74-4de6-bf79-c76b3662e9ef](https://github.com/DaoCloud/DaoCloud-docs/assets/95007522/2fcca4c7-8130-4f18-8275-5e9111af3f59)

**Comment by windsonsea** [comment]
https://docs.daocloud.io/ghippo/user-guide/report-billing/index.html
