### ISSUE TITLE
【ghippo】【zh】配置反向代理地址不成功

### ISSUE THREAD

**Issue by wlq1212** [DaoCloud/DaoCloud-docs#3197]
文档中需天机步骤
1、需要添加repo：
helm repo add ghippo http://{点火ip}:8081
2、
把${GHIPPO_VALUES_BAK} 内的imageRegistry 的/release.daocloud.io去掉。

**Comment by Fan-Lin** [comment]
没理解怎么修改，没找到定位内容。
https://docs.daocloud.io/ghippo/install/reverse-proxy/
