### ISSUE TITLE
调度模式建议增加相关的文字说明和解释

### ISSUE THREAD

**Issue by zgfh** [DaoCloud/DaoCloud-docs#321]
**Describe the bug**
![image](https://user-images.githubusercontent.com/11729624/197928914-082e6c50-ce95-432a-b5e8-302190e36dab.png)
调度模式建议增加相关的文字说明和解释
目前不知道“聚合“和”动态权重“ 是什么效果

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by windsonsea** [comment]
Noted, thanks. Will improve soon.

**Comment by windsonsea** [comment]
@SAMZONG we need to add more text about those parameters about kairship.

**Comment by SAMZONG** [comment]
Great idea, we will add more descriptions in future.

**Comment by Michelle951** [comment]
已优化，点击问号可查看解释：
<img width="1105" alt="image" src="https://github.com/DaoCloud/DaoCloud-docs/assets/35519562/bbe6afd9-e967-4a19-a70f-a43ef04b5ebe">
