### ISSUE TITLE
[多云编排] 中文文档需要更新

### ISSUE THREAD

**Issue by Fan-Lin** [DaoCloud/DaoCloud-docs#3221]
https://docs.daocloud.io/kairship/policy/override.html#_3
**以下内容或需删减**

![image](https://github.com/DaoCloud/DaoCloud-docs/assets/150505581/d10551be-db9c-41b1-8c81-1a7646f35d6f)

**Comment by windsonsea** [comment]
此问题已修复，参见：
https://docs.daocloud.io/kairship/policy/override.html#__tabbed_1_2
