### ISSUE TITLE
【可观测性】【中英文】英文环境下，只有涉及到能力说明的时候才需要使用Observability，其他都应该使用Insight模块名

### ISSUE THREAD

**Issue by Penguin-zlh** [DaoCloud/DaoCloud-docs#3246]
**Describe the bug**
【可观测性】【中英文】英文环境下，只有涉及到能力说明的时候才需要使用Observability，其他都应该使用Insight模块名

<img width="1185" alt="image" src="https://github.com/DaoCloud/DaoCloud-docs/assets/57695165/32df5277-63ad-48e1-b76d-a349bc969db2">

** 备注：通篇排查

**Comment by windsonsea** [comment]
此问题已 fixed，参见：
https://docs.daocloud.io/en/insight/intro/permission/
