### ISSUE TITLE
【可观测性】【中英文】英文环境下，大部分文档对应图片未更新上去

### ISSUE THREAD

**Issue by Penguin-zlh** [DaoCloud/DaoCloud-docs#3247]
**Describe the bug**
【可观测性】【中英文】英文环境下，大部分文档对应图片未更新上去

中文
<img width="1216" alt="image" src="https://github.com/DaoCloud/DaoCloud-docs/assets/57695165/1ed18292-804b-4719-bb9a-5a1b588c873f">

英文
<img width="1146" alt="image" src="https://github.com/DaoCloud/DaoCloud-docs/assets/57695165/b1a23447-f4fe-4f3c-8310-fd1124756567">

** 备注：全部需要补充

**Comment by windsonsea** [comment]
要修复的页面link：
https://docs.daocloud.io/en/insight/user-guide/dashboard/overview/
