### ISSUE TITLE
【安装器】【i18n】Perform the offline installation 相关流程错误

### ISSUE THREAD

**Issue by FloatXD** [DaoCloud/DaoCloud-docs#3287]
![图片](https://github.com/DaoCloud/DaoCloud-docs/assets/76234281/8f1abe58-2080-4c0d-8147-c7bfd4c01348)
![图片](https://github.com/DaoCloud/DaoCloud-docs/assets/76234281/b98b7ddf-e504-431e-ab4d-594b16458189)

**Comment by Fan-Lin** [comment]
具体指哪里的流程有问题呢，没有看懂。
