### ISSUE TITLE
【网络】i18n-Terway 的 「usage」英文界面图片引用失败与中文未保持一致。

### ISSUE THREAD

**Issue by ty-dc** [DaoCloud/DaoCloud-docs#3298]
#### 英文
https://docs.daocloud.io/en/network/modules/aliyun-terway/usage.html#install-terway-cni-plugin

![image](https://github.com/DaoCloud/DaoCloud-docs/assets/101157744/2a1df6c1-f751-4f18-ab76-aefa8153690d)

#### 中文
https://docs.daocloud.io/network/modules/aliyun-terway/usage.html#terway-cni

![image](https://github.com/DaoCloud/DaoCloud-docs/assets/101157744/772c931e-3c00-48e5-9024-bf8dee47b46e)

**Comment by windsonsea** [comment]
没有阿里云 demo 环境，暂时只能放中文的图了
