### ISSUE TITLE
【中间件】【PostgreSQL】【i18n】“快速入门功能”缺少图片

### ISSUE THREAD

**Issue by fangbin9527** [DaoCloud/DaoCloud-docs#3315]
英文文档缺少图片
https://docs.daocloud.io/en/middleware/postgresql/user-guide/create.html

![image](https://github.com/DaoCloud/DaoCloud-docs/assets/71134088/afb3d87b-800e-4a8d-a025-2b9ce15c2d48)
![image](https://github.com/DaoCloud/DaoCloud-docs/assets/71134088/b6c27925-a175-46f5-ae62-1ce038f8f1af)

**Comment by Fan-Lin** [comment]
第四步**手工设置工作负载反亲和**

中文文档图片模糊，`编辑YAML`，修改字段步骤无法复刻。等待中文文档更新后，再相应补充英文文档图片。

https://docs.daocloud.io/middleware/postgresql/user-guide/antiaffinity/

P.S. “手工”设置是否改为“手动设置”？

**Comment by windsonsea** [comment]
图片已添加：
https://docs.daocloud.io/en/middleware/postgresql/user-guide/create.html
