### ISSUE TITLE
【虚拟机】创建虚拟机的时候提供的yaml文件不可用

### ISSUE THREAD

**Issue by shijinye** [DaoCloud/DaoCloud-docs#3335]
**Describe the bug**

【虚拟机】创建虚拟机的时候提供的yaml文件不可用

![image](https://github.com/DaoCloud/DaoCloud-docs/assets/36811869/28221218-0695-4913-afab-137c491c5e87)

**To Reproduce**

2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by wlp1153468871** [comment]
已经fix：https://github.com/DaoCloud/DaoCloud-docs/pull/3899
