### ISSUE TITLE
【virtnest】安装虚机命令显示，可以替换为已经存在的版本号

### ISSUE THREAD

**Issue by sangy001** [DaoCloud/DaoCloud-docs#3376]
当前virtnest版本最高为0.4.0，0.9版本不存在
![image](https://github.com/DaoCloud/DaoCloud-docs/assets/37102834/8fcb9eda-1fab-42ae-89ff-26aff3e9b2e7)

展示样例建议可以替换为已存在的virtnest版本
https://docs.daocloud.io/virtnest/intro/install/#virtnest-helm
![image](https://github.com/DaoCloud/DaoCloud-docs/assets/37102834/b25dbc04-7ea8-4566-9b4b-27159cd20d0d)

**Comment by wlp1153468871** [comment]
#3912
