### ISSUE TITLE
【virtnest】文档与UI页面翻译不一致问题

### ISSUE THREAD

**Issue by sangy001** [DaoCloud/DaoCloud-docs#3381]
https://docs.daocloud.io/en/virtnest/quick-start/create-tep.html
![企业微信截图_c7568915-ed27-4192-a9a9-7b53d214c3c8](https://github.com/DaoCloud/DaoCloud-docs/assets/37102834/752c56d5-4994-4c72-8334-f1e91eca0f7c)

实际操作页面
![image](https://github.com/DaoCloud/DaoCloud-docs/assets/37102834/0e97dc49-cb2e-4a4d-83aa-bdd797b23646)

**Comment by Fan-Lin** [comment]
模板创建界面，文档图片和UI界面是一致的。第二张图是通过镜像创建的页面。
