### ISSUE TITLE
insight 的权限角色未找到

### ISSUE THREAD

**Issue by zgfh** [DaoCloud/DaoCloud-docs#339]
**Describe the bug**
如下图，这几个角色没找到，如”NS Admin “，在全局管理-工作空间没有，全局角色也没有
https://docs.daocloud.io/ghippo/permissions/insight/
![image](https://user-images.githubusercontent.com/11729624/198233064-fc7c49d0-b388-482a-9268-36ca31fac61b.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by windsonsea** [comment]
@justedennnnn  帮忙看看，可以加一些说明或链接，怎么找到这个角色
