### ISSUE TITLE
【容器管理】多架构Helm应用页面的命令有误

### ISSUE THREAD

**Issue by shijinye** [DaoCloud/DaoCloud-docs#3502]
**Describe the bug**
【容器管理】多架构Helm应用页面的命令有误
![image](https://github.com/DaoCloud/DaoCloud-docs/assets/36811869/87eea67e-aad4-4b30-bfe7-780fcb075fd0)

**To Reproduce**

2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by windsonsea** [comment]
这正确的命令应该是什么？

**Comment by shijinye** [comment]
命令中间多了一个空格 import-addon
