### ISSUE TITLE
开启/关闭审计日志文档中审计日志 Policy 文件格式有误并且有些地方带中文有问题

### ISSUE THREAD

**Issue by shijinye** [DaoCloud/DaoCloud-docs#352]
文档地址：https://docs.daocloud.io/ghippo/04UserGuide/open-audit/

问题：
![image](https://user-images.githubusercontent.com/36811869/198537860-e5842009-e188-45e6-896d-929c29744661.png)
![image](https://user-images.githubusercontent.com/36811869/198537871-59641f5f-9357-44b5-8fbf-f8a1c715b116.png)

**Comment by windsonsea** [comment]
@yitingdc @lemontrees123
