### ISSUE TITLE
【容器管理】为全局服务集群的工作节点扩容在火种机kind集群内创建cluster.kubean.io资源，需要增加一步，下面hostsConfRef、kubeconfRed以及varsConfRef中的name需要和已有的集群name保持一致

### ISSUE THREAD

**Issue by shijinye** [DaoCloud/DaoCloud-docs#3553]
**Describe the bug**
【容器管理】为全局服务集群的工作节点扩容在火种机kind集群内创建cluster.kubean.io资源，需要增加一步，下面hostsConfRef、kubeconfRed以及varsConfRef中的name需要和已有的集群name保持一致

![image](https://github.com/DaoCloud/DaoCloud-docs/assets/36811869/9d35d1d5-6ece-45a2-885a-54e241ddb13f)

命令查询：kind get clusters

**To Reproduce**

2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by windsonsea** [comment]
能把 link 贴一下吗，issue 标题几个字就行，文字放在正文

这是需要增加一个注释？

https://docs.daocloud.io/kpanda/best-practice/add-worker-node-on-global/

**Comment by shijinye** [comment]
产品已做过调整
![image](https://github.com/DaoCloud/DaoCloud-docs/assets/36811869/8dd9da7e-f92a-4464-8d7a-ee2145bae6ba)
