### ISSUE TITLE
【容器管理】为全局服务集群的工作节点扩容中拷贝config.toml文件到火种节点，建议增加一步，确认runc的正确路径

### ISSUE THREAD

**Issue by shijinye** [DaoCloud/DaoCloud-docs#3554]
**Describe the bug**

<img width="951" alt="企业微信截图_374ed009-11f4-4e69-a8c0-33107cef0138" src="https://github.com/DaoCloud/DaoCloud-docs/assets/36811869/cf254c03-9eec-4c75-8063-070deaf4fa93">

<img width="719" alt="image" src="https://github.com/DaoCloud/DaoCloud-docs/assets/36811869/3c67eb97-b5c9-4e8b-bdfa-8937ebec22fe">

runc 路径命令 ： type runc

如果不同的话，需要替换到正确的路径

**To Reproduce**

2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by windsonsea** [comment]
https://docs.daocloud.io/kpanda/best-practice/add-worker-node-on-global/

**Comment by windsonsea** [comment]
不明白啥意思，这条命令要加到哪儿的？

**Comment by shijinye** [comment]
这篇文档产品已经调整过
