### ISSUE TITLE
服务网格的学习路径页面有格式乱码

### ISSUE THREAD

**Issue by tukwila** [DaoCloud/DaoCloud-docs#3652]
**Describe the bug**

https://docs.daocloud.io/mspider/intro/

文档中‘服务网格的学习路径’有乱码：

![image](https://github.com/DaoCloud/DaoCloud-docs/assets/13757056/a1052cae-74dd-4705-a0c5-4dcaae5c85c5)

**Comment by windsonsea** [comment]
这3行是定义颜色的，目前该页面显示正常，所以此 issue will be closed
