### ISSUE TITLE
kpanda release v0.12.1

### ISSUE THREAD

**Issue by cleverhu** [DaoCloud/DaoCloud-docs#366]
**Is your feature request related to a problem? Please describe.**
kpanda release v0.12.1, the document needs to be updated.
**Describe the solution you'd like**
kpanda has release v0.12.0 and v0.12.1, please update the doc.
https://gitlab.daocloud.cn/ndx/engineering/kpanda/-/releases#v0.12.1
https://gitlab.daocloud.cn/ndx/engineering/kpanda/-/releases#v0.12.0

**Describe alternatives you've considered**

**Additional context**

**Comment by chaunceyjiang** [comment]
https://github.com/DaoCloud/DaoCloud-docs/issues/348#issuecomment-1294505733

**Comment by windsonsea** [comment]
Noted. Will add in.
