### ISSUE TITLE
【安装器】安装说明链接失效

### ISSUE THREAD

**Issue by FloatXD** [DaoCloud/DaoCloud-docs#3661]
![图片](https://github.com/DaoCloud/DaoCloud-docs/assets/76234281/7ae4101e-4dac-4fa2-aa8e-956b3bbdfc3d)
![图片](https://github.com/DaoCloud/DaoCloud-docs/assets/76234281/a34b055a-1e40-44d2-ad71-7df3426f8ff1)

**Comment by windsonsea** [comment]
https://docs.daocloud.io/install/community/k8s/k8s-dce-deploy/

目前这个 link 已修复，so this issue will be closed.
