### ISSUE TITLE
kairship released v0.3.4 version

### ISSUE THREAD

**Issue by calvin0327** [DaoCloud/DaoCloud-docs#370]
**Is your feature request related to a problem? Please describe.**
kairship released v0.3.4 version, the document needs to be updated.

**Describe the solution you'd like**
kairship released v0.3.4, v0.3.3 and v0.30 version, please update the doc.
https://gitlab.daocloud.cn/ndx/engineering/kairship/-/releases/v0.3.4
https://gitlab.daocloud.cn/ndx/engineering/kairship/-/releases/v0.3.3
https://gitlab.daocloud.cn/ndx/engineering/kairship/-/releases/v0.3.0

**Describe alternatives you've considered**

**Additional context**

**Comment by chaunceyjiang** [comment]
https://github.com/DaoCloud/DaoCloud-docs/issues/348#issuecomment-1294505733

**Comment by windsonsea** [comment]
Noted. Will add in.
