### ISSUE TITLE
【服务网格】tcp探针的空闲超时时长解释成“最短空闲时间”有误

### ISSUE THREAD

**Issue by git-jxj** [DaoCloud/DaoCloud-docs#3724]
<img width="924" alt="image" src="https://github.com/DaoCloud/DaoCloud-docs/assets/65210887/13818e91-73bf-40f5-bcbf-c5445c2c14d8">

https://docs.daocloud.io/mspider/intro/features.html#_2

**Comment by windsonsea** [comment]
这个应该改成什么的？

**Comment by git-jxj** [comment]
<img width="1023" alt="image" src="https://github.com/DaoCloud/DaoCloud-docs/assets/65210887/7c823852-fb93-4bf7-9a63-5df3a0d508e3">

按照界面解释吧，这个最短空闲时间确实看不懂
