### ISSUE TITLE
【服务网格】网格架构的模块组成已变化

### ISSUE THREAD

**Issue by git-jxj** [DaoCloud/DaoCloud-docs#3740]
<img width="1450" alt="image" src="https://github.com/DaoCloud/DaoCloud-docs/assets/65210887/b50d0edd-8f2f-466c-acce-4caefd0d76c2">

https://docs.daocloud.io/mspider/intro/comp-archi-ui/architect.html#_2

**Comment by windsonsea** [comment]
Both zh and en have fixed this issue in:

PR https://github.com/DaoCloud/DaoCloud-docs/pull/3914
