### ISSUE TITLE
【服务网格】新增了开启私有镜像仓库以及边车发现范围限制的功能

### ISSUE THREAD

**Issue by git-jxj** [DaoCloud/DaoCloud-docs#3759]
<img width="1463" alt="image" src="https://github.com/DaoCloud/DaoCloud-docs/assets/65210887/6bd70803-08c7-4853-9376-71483f8f65ea">

https://docs.daocloud.io/mspider/user-guide/service-mesh/index.html

**Comment by windsonsea** [comment]
这个不会配，什么情况下会出现这 2 个功能的？

**Comment by git-jxj** [comment]
创建网格实例时就有，前不久的新功能

**Comment by windsonsea** [comment]
#3766  是从 demo-dev 截的新图，没有发现这2项

**Comment by windsonsea** [comment]
懂了，issue 写得具体点，例如：

- 第 5 步截图有变化了
