### ISSUE TITLE
【云边协同】功能特性目前没有应用网格，能否加入

### ISSUE THREAD

**Issue by liyuerich** [DaoCloud/DaoCloud-docs#3833]
【云边协同】功能特性目前没有应用网格，能否加入

https://docs.daocloud.io/kant/intro/features.html#_3

**Comment by windsonsea** [comment]
cc @zhiyingfang2022 , seems the architecture image shall be updated too.

**Comment by zhiyingfang2022** [comment]
@liyuerich @windsonsea Thanks for the suggestion, I will update the features as a whole.
