### ISSUE TITLE
视频全部自动播放

### ISSUE THREAD

**Issue by kebe7jun** [DaoCloud/DaoCloud-docs#395]
**Describe the bug**
进入 https://docs.daocloud.io/videos/mspider/ ，所有的视频全部一起播放了。

**Comment by windsonsea** [comment]
经确认，目前手机版是会这样全部自动播放，PC 没这个问题。

https://docs.daocloud.io/videos/mspider

@SAMZONG

**Comment by kebe7jun** [comment]
我的电脑也会。
