### ISSUE TITLE
容器管理 - 在集群中部署第二调度器文档中示例缺少参数项

### ISSUE THREAD

**Issue by shijinye** [DaoCloud/DaoCloud-docs#3966]
**Describe the bug**
容器管理 - 在集群中部署第二调度器文档中示例缺少参数项
<img width="1416" alt="image" src="https://github.com/DaoCloud/DaoCloud-docs/assets/36811869/ab011335-6b25-49c5-8fbe-d19f3cf84f8a">

**To Reproduce**

2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by zhiyingfang2022** [comment]
done.
