### ISSUE TITLE
容器管理 - 在集群中部署第二调度器文档中yaml格式存在问题 

### ISSUE THREAD

**Issue by shijinye** [DaoCloud/DaoCloud-docs#3975]
**Describe the bug**
容器管理 - 在集群中部署第二调度器文档中yaml格式存在问题 
<img width="1212" alt="image" src="https://github.com/DaoCloud/DaoCloud-docs/assets/36811869/848bb35d-4bad-4beb-bac6-0b83d80866fe">

**To Reproduce**

2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by zhiyingfang2022** [comment]
done.
