### ISSUE TITLE
容器管理 - 在集群中部署第二调度器文档中scheduler name有误

### ISSUE THREAD

**Issue by shijinye** [DaoCloud/DaoCloud-docs#3977]
**Describe the bug**
容器管理 - 在集群中部署第二调度器文档中scheduler name有误
<img width="1439" alt="image" src="https://github.com/DaoCloud/DaoCloud-docs/assets/36811869/3706eb91-1898-472f-8ffd-2c2a9396f9f5">
<img width="1347" alt="image" src="https://github.com/DaoCloud/DaoCloud-docs/assets/36811869/91e6a482-49c1-4240-8023-15940ce3f3ca">

**To Reproduce**

2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by zhiyingfang2022** [comment]
done.
