### ISSUE TITLE
容器管理 - 在集群中部署第二调度器文档中配置vgpu参数建议文档中提供一些详细的步骤，而不是只写一个参数并没有截图

### ISSUE THREAD

**Issue by shijinye** [DaoCloud/DaoCloud-docs#3978]
**Describe the bug**
容器管理 - 在集群中部署第二调度器文档中配置vgpu参数建议文档中提供一些详细的步骤，而不是只写一个参数并没有截图
<img width="1430" alt="image" src="https://github.com/DaoCloud/DaoCloud-docs/assets/36811869/46002209-c9cd-4465-aa13-8bcd377736cb">
<img width="1320" alt="image" src="https://github.com/DaoCloud/DaoCloud-docs/assets/36811869/1f7dbdba-f958-4af8-95b0-803bcfbfe550">

**To Reproduce**

2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by zhiyingfang2022** [comment]
done:https://github.com/DaoCloud/DaoCloud-docs/pull/4010
