### ISSUE TITLE
容器管理 - 在集群中部署第二调度器文档中extender的yaml格式有问题

### ISSUE THREAD

**Issue by shijinye** [DaoCloud/DaoCloud-docs#3979]
**Describe the bug**
容器管理 - 在集群中部署第二调度器文档中extender的yaml格式有问题
<img width="1383" alt="image" src="https://github.com/DaoCloud/DaoCloud-docs/assets/36811869/6a2832e0-2f6c-42df-8c02-e27432c362fe">

**To Reproduce**

2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by zhiyingfang2022** [comment]
done.
