### ISSUE TITLE
容器管理 - 在集群中部署第二调度器文档中extender中urlprefix的获取能否写的更详细一点？

### ISSUE THREAD

**Issue by shijinye** [DaoCloud/DaoCloud-docs#3980]
**Describe the bug**
容器管理 - 在集群中部署第二调度器文档中extender中urlprefix的获取能否写的更详细一点？
<img width="887" alt="企业微信截图_fd6c36a0-a9c1-430d-b246-be4daa6bb465" src="https://github.com/DaoCloud/DaoCloud-docs/assets/36811869/1e8b9338-a17c-4c46-aedc-e98a957e52f8">

**To Reproduce**

2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by zhiyingfang2022** [comment]
done：https://github.com/DaoCloud/DaoCloud-docs/pull/4010
