### ISSUE TITLE
容器管理 - 在集群中部署第二调度器文档中extender配置完成后，scheduler存在两个服务，是否应该标明重启哪个服务？

### ISSUE THREAD

**Issue by shijinye** [DaoCloud/DaoCloud-docs#3981]
**Describe the bug**
容器管理 - 在集群中部署第二调度器文档中extender配置完成后，scheduler存在两个服务，是否应该标明重启哪个服务？
<img width="1403" alt="image" src="https://github.com/DaoCloud/DaoCloud-docs/assets/36811869/f5041127-90a4-45e8-add1-45d50fd34ef4">

**To Reproduce**

2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by zhiyingfang2022** [comment]
done:https://github.com/DaoCloud/DaoCloud-docs/pull/4010
