### ISSUE TITLE
容器管理 - 在集群中部署第二调度器文档中helm应用安装开始应该是应用这个调度器而不属于安装这一块，建议标题进行区分

### ISSUE THREAD

**Issue by shijinye** [DaoCloud/DaoCloud-docs#3982]
**Describe the bug**
容器管理 - 在集群中部署第二调度器文档中helm应用安装开始应该是应用这个调度器而不属于安装这一块，建议标题进行区分
<img width="1339" alt="image" src="https://github.com/DaoCloud/DaoCloud-docs/assets/36811869/9ac4f587-0d65-4e5b-b504-4932ba47cfa9">

**To Reproduce**

2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by zhiyingfang2022** [comment]
done.
