### ISSUE TITLE
上传helm模版安装cm-push插件存在前提条件，建议增加提示

### ISSUE THREAD

**Issue by shijinye** [DaoCloud/DaoCloud-docs#4109]
**Describe the bug**
![image](https://github.com/DaoCloud/DaoCloud-docs/assets/36811869/e68ba194-65af-4890-a35d-b9ffafc698ad)

**To Reproduce**

2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by windsonsea** [comment]
Already fixed in #4436
