### ISSUE TITLE
d.run算法开发notebook选择纯CPU资源实际会挂载节点上所有GPU卡

### ISSUE THREAD

**Issue by king-jingxiang** [DaoCloud/DaoCloud-docs#4121]
![image](https://github.com/DaoCloud/DaoCloud-docs/assets/32818529/e009713d-5e70-4a15-b913-53000a4e3da4)
![image](https://github.com/DaoCloud/DaoCloud-docs/assets/32818529/30ef5207-9f8d-46ee-86a4-a7168e6fd210)

**Comment by king-jingxiang** [comment]
add container env `NVIDIA_VISIBLE_DEVICES=""` to solve this problem

**Comment by windsonsea** [comment]
cc @samzong
