### ISSUE TITLE
文档链接失效

### ISSUE THREAD

**Issue by wongzigii** [DaoCloud/DaoCloud-docs#42]
- 如何联系 DaoCloud 的技术支持？
- DaoCloud 提供免费资源吗？
- 如何在容器中保存数据？
- DaoCloud提供私有化部署吗？
- DaoCloud 的架构和核心技术是什么？
- DaoCloud 招人吗？

等页面的 _帮忙完善文档_ 链接失效。

**Comment by SAMZONG** [comment]
文档已修复.
