### ISSUE TITLE
文档与 GitHub 不一致

### ISSUE THREAD

**Issue by Pandoraemon** [DaoCloud/DaoCloud-docs#43]
2 常见问题
- DaoCloud 加速器

文档与GitHub不一致，Docker for Mac 标题下 ”Docker for Windows 可以让您在 Mac 上使用 Docker“ 应为”Docker for Mac" 。

**Comment by allencloud** [comment]
Thanks for your contribution.
DaoCloud would appreciate it if you could submit a PR to fix this. :)

**Comment by Pandoraemon** [comment]
但是我觉得这个问题可能是网站上的文档没有从 GitHub 更新过来，因为我看 GitHub 上的像是最新的版本。

**Comment by windsonsea** [comment]
/close

due to outdated
