### ISSUE TITLE
【虚拟机】安装依赖检查CPU支持脚本有报错

### ISSUE THREAD

**Issue by liyuerich** [DaoCloud/DaoCloud-docs#4373]
https://docs.daocloud.io/virtnest/install/install-dependency/#_2

CPU 需支持 x86-64-v2 及以上的指令集。您可以使用以下脚本检查当前节点的 CPU 是否支持：

<img width="909" alt="image" src="https://github.com/DaoCloud/DaoCloud-docs/assets/97269208/afb56be8-4c34-479f-947f-92882812f1a7">

**Comment by windsonsea** [comment]
@wlp1153468871

**Comment by scydas** [comment]
该报错不影响，检查结果
