### ISSUE TITLE
Kylin v10 sp2 的 ISO 离线包地址打不开了

### ISSUE THREAD

**Issue by windsonsea** [DaoCloud/DaoCloud-docs#4454]
https://docs.daocloud.io/kpanda/best-practice/multi-arch#iso-kylin-v10-sp2

Kylin v10 sp2 的 ISO 离线包地址打不开了：

![企业微信截图_9a4dfc83-a4fb-4a4c-aef8-f7e25d719ed2](https://github.com/DaoCloud/DaoCloud-docs/assets/79828097/e8216acc-098f-4d5b-8b4c-65050631ce63)

Issue 来源：售前songtao

**Comment by lemontrees123** [comment]
已更新：https://github.com/DaoCloud/DaoCloud-docs/pull/4457
