### ISSUE TITLE
配置 SSH 公钥中生成密钥命令出现错误

### ISSUE THREAD

**Issue by shijinye** [DaoCloud/DaoCloud-docs#4458]
**Describe the bug**
![企业微信截图_15269c7b-42df-49dc-8e3a-eeea1ab9a33b](https://github.com/DaoCloud/DaoCloud-docs/assets/36811869/6f3e19e4-9a2f-45ca-8716-6ea6112dd584)

**To Reproduce**

2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by windsonsea** [comment]
oh, @shijinye could you provide some sugestions to fix the bug?

**Comment by shijinye** [comment]
> oh, @shijinye could you provide some sugestions to fix the bug?

ssh-keygen

**Comment by windsonsea** [comment]
ok, understood, thanks.
