### ISSUE TITLE
GPU监控指标名称有误

### ISSUE THREAD

**Issue by shijinye** [DaoCloud/DaoCloud-docs#4460]
**Describe the bug**
![image](https://github.com/DaoCloud/DaoCloud-docs/assets/36811869/f6328e41-0de9-47fa-ae66-032d2cc9316e)

**To Reproduce**

2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ModetaNiu** [comment]
fixed, see https://docs.daocloud.io/kpanda/user-guide/gpu/gpu-metrics.html#_1
