### ISSUE TITLE
GPU资源动态调节文档中如果使用burn的话，调整前后的效果并没有体现出来

### ISSUE THREAD

**Issue by shijinye** [DaoCloud/DaoCloud-docs#4582]
**Is your feature request related to a problem? Please describe.**
<img width="1317" alt="image" src="https://github.com/DaoCloud/DaoCloud-docs/assets/36811869/53e99da8-2e65-4afc-9c1e-614bb0e675d3">

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by windsonsea** [comment]
前后应该是怎样的？
