### ISSUE TITLE
构建 Red Hat 7.9 离线 yum 源 文档中给到的“ kubean的代码仓库”地址有误

### ISSUE THREAD

**Issue by shijinye** [DaoCloud/DaoCloud-docs#4615]
**Describe the bug**
<img width="1212" alt="image" src="https://github.com/DaoCloud/DaoCloud-docs/assets/36811869/8a995df7-27b1-4e03-849e-74777321816d">

**To Reproduce**

2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by windsonsea** [comment]
每个 issue 可以把无用信息删除，然后贴个链接呀 😓

**Comment by shijinye** [comment]
> 每个 issue 可以把无用信息删除，然后贴个链接呀 😓
> 
> * 文档站是一个迷宫，你加了 link 就不用再寻路了
> * 不要只是说错，如果还能指出什么是正确的，那就更好了

文档地址：https://docs.daocloud.io/kpanda/user-guide/gpu/nvidia/yum_source_redhat7_9.html

![image](https://github.com/DaoCloud/DaoCloud-docs/assets/36811869/e7ca2379-3866-4242-8946-be6f33bf2034)

**Comment by windsonsea** [comment]
非常感谢
