### ISSUE TITLE
加入 EOL(End of life) 描述

### ISSUE THREAD

**Issue by yankay** [DaoCloud/DaoCloud-docs#4635]
加入 EOL 描述。包括 DCE 3，DCE 4.

**Comment by windsonsea** [comment]
参见产品支持政策：
https://docs.daocloud.io/test/support/#_9

**Comment by yankay** [comment]
> 参见产品支持政策： https://docs.daocloud.io/test/support/#_9

赞👍

还需要一个这样的 有明确日期的表格，类似 ： https://endoflife.date/red-hat-openshift

**Comment by yankay** [comment]
> 参见产品支持政策： https://docs.daocloud.io/test/support/#_9

可能还需要一个表格 https://endoflife.date/red-hat-openshift

**Comment by liyuerich** [comment]
@windsonsea  ，这里的文字是不是应该为 “支持”？
![企业微信截图_de889e47-568b-47dd-b747-56a776156784](https://github.com/DaoCloud/DaoCloud-docs/assets/97269208/43635b36-86d7-4212-bd6e-c96ab012c489)

**Comment by yankay** [comment]
不知道有木有可能登记到 https://endoflife.date/recommendations 上面。

**Comment by windsonsea** [comment]
@liyuerich 啊额，火眼晶晶，是 typo

**Comment by windsonsea** [comment]
@yankay 我试试去提个 PR

**Comment by windsonsea** [comment]
https://endoflife.date/dce

This eol is merged and released and this issue will be closed, thanks.
