### ISSUE TITLE
kairship released v0.4.0 version

### ISSUE THREAD

**Issue by calvin0327** [DaoCloud/DaoCloud-docs#469]
**Is your feature request related to a problem? Please describe.**
kairship released v0.4.0 version, the document needs to be updated.

**Describe the solution you'd like**
kairship released v0.4.0 version, please update the doc.
https://gitlab.daocloud.cn/ndx/engineering/kairship/-/releases/v0.4.0

**Describe alternatives you've considered**

**Additional context**

**Comment by windsonsea** [comment]
👍

**Comment by windsonsea** [comment]
已体现在：https://docs.daocloud.io/kairship/01product/release-notes/
