### ISSUE TITLE
生命周期公告，错别字

### ISSUE THREAD

**Issue by liyuerich** [DaoCloud/DaoCloud-docs#4837]
https://docs.daocloud.io/test/support/#_9

生命周期公告，错别字

![image](https://github.com/DaoCloud/DaoCloud-docs/assets/97269208/059b5a6a-7818-4ce5-b627-0895826d3ee8)

**Comment by ModetaNiu** [comment]
Already fixed: https://docs.daocloud.io/dce/support/
