### ISSUE TITLE
【存储】'kubelet' 拼写错误

### ISSUE THREAD

**Issue by jzhupup** [DaoCloud/DaoCloud-docs#4977]
https://docs.daocloud.io/storage/solutions/longhorn/

![img_v3_02d2_853823ff-2e32-4ba6-a456-3abceb7f4acg](https://github.com/user-attachments/assets/e6db5739-74e0-4e74-ae0c-4abb9bf43c94)

**Comment by liyuerich** [comment]
是 “kubelet” 非 “kubelete"
