### ISSUE TITLE
智能算力模块，预热中和运行中的icon颜色不一致，叫法也不同

### ISSUE THREAD

**Issue by wlp1153468871** [DaoCloud/DaoCloud-docs#5008]
![image](https://github.com/user-attachments/assets/0338132b-0a7f-40be-94e0-01c2e37f0e99)
<img width="1418" alt="image" src="https://github.com/user-attachments/assets/5b214218-496b-49f2-a662-8195de4670db">
已经就绪、运行中、预热中这些状态的icon的颜色不同

**Comment by samzong** [comment]
已修复完成
