### ISSUE TITLE
存储：创建storage class 需要提供产品化方式安装，以及必备的字段信息

### ISSUE THREAD

**Issue by qiupingdai** [DaoCloud/DaoCloud-docs#5097]
https://docs.daocloud.io/storage/hwameistor/resources/storageclass/
目前文档只有命令安装，并且没有和kpanda 存储池联动，需要优化
<img width="979" alt="image" src="https://github.com/user-attachments/assets/24334c68-ad98-4cbf-9b1a-d2173d601391">

**Comment by jzhupup** [comment]
https://github.com/DaoCloud/DaoCloud-docs/pull/5365
