### ISSUE TITLE
全局管理：ldap 已支持用户名映射、用户对象过滤器字段，以及优化了页面

### ISSUE THREAD

**Issue by lemontrees123** [DaoCloud/DaoCloud-docs#5112]
ldap 已支持用户名映射、用户对象过滤器字段，以及优化了页面，文档中图片和字段未更新

https://docs.daocloud.io/ghippo/user-guide/access-control/ldap.html

![image](https://github.com/user-attachments/assets/cf38d1c7-02c5-48cd-96ed-011d0d08b074)

**Comment by windsonsea** [comment]
目标页面为：
https://docs.daocloud.io/ghippo/user-guide/access-control/ldap/

**Comment by WANG0608GitHub** [comment]
fix #5421
