### ISSUE TITLE
【镜像仓库】托管harbor 有一个新的 操作， 状态检查， 文档里可以增加一下说明

### ISSUE THREAD

**Issue by liyuerich** [DaoCloud/DaoCloud-docs#5150]
https://docs.daocloud.io/kangaroo/managed/harbor.html

托管harbor 有一个新的 操作， 状态检查， 文档里可以增加一下说明

![image](https://github.com/user-attachments/assets/542ce43e-6407-4c31-955c-b94ba0c3602f)

**Comment by ModetaNiu** [comment]
页面已更新，见 #5209
