### ISSUE TITLE
【智能算力】快速上手，创建notebook，pvc 和数据集使用的pvc 有点混淆，建议如下：

### ISSUE THREAD

**Issue by liyuerich** [DaoCloud/DaoCloud-docs#5252]
https://docs.daocloud.io/baize/developer/quick-start/

快速上手，创建notebook，pvc 和数据集使用的pvc 有点混淆，建议如下：

1、创建数据集，建议命名为 pvc-model，因为看后面创建notebook的引用，这里是存放 “训练结束的模型和日志”

需要提前创建好对应的pvc：  pvc-model

![image](https://github.com/user-attachments/assets/3a30e625-7940-4f54-bf68-b3a60c9686f6)

2、创建notebook， 用户目录-持久化数据，需要提前创建好pvc，pvc-empty。 如果这里的pvc 名字使用了pvc-empty，  就和第一步的数据集名字重复了， 所以建议从第一步开始， 就统一用pvc-model

![image](https://github.com/user-attachments/assets/a00b484f-91d2-43cb-b09e-d0a40c40039e)

这里的notebook的图片也是旧的， 可以更新

**Comment by samzong** [comment]
数据集功能有优化，会在下个月初更新.
