### ISSUE TITLE
【智能算力】快速上手， 开启任务分析的配置没有说明， 创建任务的图片也是旧的 ，需要更新

### ISSUE THREAD

**Issue by liyuerich** [DaoCloud/DaoCloud-docs#5255]
https://docs.daocloud.io/baize/developer/quick-start/

快速上手， 开启任务分析的配置没有说明， 创建任务的图片也是旧的 ，需要更新

![image](https://github.com/user-attachments/assets/5cae6810-7d14-4a32-a271-76206faf522d)

**Comment by windsonsea** [comment]
@samzong 怎么开启 Tensorboard 任务分析的，没找到开关

**Comment by samzong** [comment]
![image](https://github.com/user-attachments/assets/438cc0c7-9524-47f4-b3da-b7fda992062a)

在 创建任务/创建Notebook，第三步，有对应的配置选项。
