### ISSUE TITLE
【安装器】升级dce5组件，安装步骤下载后发现并没有offline/sample目录

### ISSUE THREAD

**Issue by Tom179** [DaoCloud/DaoCloud-docs#5455]
https://docs.daocloud.io/install/upgrade.html#1-v090
安装步骤下载后发现并没有offline/sample目录
![image](https://github.com/user-attachments/assets/3303e60d-a4fc-485f-a821-65b439a04608)

![image](https://github.com/user-attachments/assets/0a4f78cb-6980-40ca-acec-409834000cc4)

**Comment by liyuerich** [comment]
good catch

**Comment by liyuerich** [comment]
从图片上看，给的文件是arm64，后面用的例子是amd，比较割裂。

**Comment by Tom179** [comment]
> 从图片上看，给的文件是arm64，后面用的例子是amd，比较割裂。

图片已更新，安装目标文件是amd64

**Comment by windsonsea** [comment]
cc @jzhupup , PTAL

**Comment by jzhupup** [comment]
建议升级到 0.21.0 版本，我更新一下
