### ISSUE TITLE
spiderpool 升级中描述的版本还是0.7.0， 目前已经发版到0.9.6 了，需要更新

### ISSUE THREAD

**Issue by liyuerich** [DaoCloud/DaoCloud-docs#5534]
https://docs.daocloud.io/network/modules/spiderpool/upgrade.html#_3

spiderpool 升级中描述的版本还是0.7.0， 目前已经发版到0.9.6 了，需要更新

![image](https://github.com/user-attachments/assets/b92218e0-b145-419a-afc6-43a6be4432fa)

**Comment by ty-dc** [comment]
fix #5535
