### ISSUE TITLE
【AI lab】需要在 Notebook 中执行 pip install -r requirements.txt 安装。 需要写清楚在 Notebook 的终端的什么目录下运行

### ISSUE THREAD

**Issue by liyuerich** [DaoCloud/DaoCloud-docs#5754]
https://docs.daocloud.io/baize/developer/quick-start/#notebook

需要在 Notebook 中执行 pip install -r requirements.txt 安装。 需要写清楚在 Notebook 的终端的什么目录下运行

![image](https://github.com/user-attachments/assets/d6861ac5-5c9d-42a8-8049-30b16cf3d9fb)

**Comment by windsonsea** [comment]
Call @samzong for help
