### ISSUE TITLE
Feature Request: 更新版本菜单名称使其看起来更加直观

### ISSUE THREAD

**Issue by samzong** [DaoCloud/DaoCloud-docs#5791]
### Problem

![image](https://github.com/user-attachments/assets/e848537a-7539-4422-982a-7a2db0f30150)

从标题仅能看到 release data, 但是对应的版本号无法直接看到

### Current Solution

点击到对应的文档查看安装器版本，然后推算之前的版本，再打开，错了再找。

### Proposed Solution

20240130 版本发布 => V0.15 版本发布 - 20240130

**Comment by windsonsea** [comment]
要试验一下，可能会有2个问题：

- 左侧 nav 会换行
- yml 对多余 `-` 的支持
