### ISSUE TITLE
docker build failed with timeout

### ISSUE THREAD

**Issue by liudonghua123** [DaoCloud/DaoCloud-docs#63]
I want to build a image which contains cling which has a lot of source code. The complete build time may be two or three hours. However I got the following errors. It seems that it was interrupted by some executor after one hour. Maybe it is the predefined rules. But I could find any documentation about this. Another question, is there some configurations on how to make it work.
![image](https://user-images.githubusercontent.com/2276718/58845743-e66f5c00-86ae-11e9-92f9-3aa886730423.png)

**Comment by eugle** [comment]
Same question

**Comment by liudonghua123** [comment]
Now the executor seems does not work at all, it was queue about a hour.

![image](https://user-images.githubusercontent.com/2276718/64923344-a706ee80-d80b-11e9-838e-b7de6b14ba2c.png)

**Comment by eugle** [comment]
I can't use it at all
![image](https://user-images.githubusercontent.com/24447931/64932445-94270500-d871-11e9-820c-e5a4c8db8062.png)
It started four days ago

**Comment by eugle** [comment]
看来你也是用的中文， @liudonghua123 ，是不是to c 服务关闭了，感觉部署服务根本没有执行，我已经尝试了几天了，没有一次成功的

**Comment by liudonghua123** [comment]
@eugle， 嗯，有可能是，我这边在 DaoCloud 的 Dashboard 的 chat 侧边栏里面联系客服也没反应

**Comment by eugle** [comment]
客服基本上不会回复的，之前也尝试过提问，你现在有什么其它的解决方案吗？改为手动部署还是使用其它的，听说github有自动部署功能了？

**Comment by liudonghua123** [comment]
目前最简单的方式可以使用github的hooks(例如https://github.com/nlf/node-github-hook/)，提交代码，会给你注册的部署服务端发送一个请求，然后运行一个本地脚本，git pull，build, docker-compose up来完成自动打包部署。
github的CI、CD还没用过，感觉可能和travis类似，可以把镜像发布到https://hub.docker.com/, 可能也会有一个执行时间限制，而且最后部署的时候也需要在本地更新才行

**Comment by eugle** [comment]
好复杂的感觉，如果部署成功，或者你的方法有效，分享一下给我吧，谢谢

**Comment by eugle** [comment]
![image](https://user-images.githubusercontent.com/24447931/64944978-2b0bb580-d8a2-11e9-84e3-350d53b85d0a.png)
客服有回复说正在排查，再 等待一下看看

**Comment by liudonghua123** [comment]
现在已经处理好了

**Comment by eugle** [comment]
可以更新了吗？
