### ISSUE TITLE
kpanda release v0.14.0

### ISSUE THREAD

**Issue by RuliXu** [DaoCloud/DaoCloud-docs#674]
**Is your feature request related to a problem? Please describe.**
Kpanda has released v0.14.0, the document needs to update.

**Describe the solution you'd like**
Kpanda has released v0.14.0, please update the doc, thank you.
https://gitlab.daocloud.cn/ndx/engineering/kpanda/-/releases#v0.14.0

**Describe alternatives you've considered**

**Additional context**

**Comment by windsonsea** [comment]
https://docs.daocloud.io/kpanda/03ProductBrief/release-notes/

已新增 rn 并上线
