### ISSUE TITLE
Add certification kubernetes Icon

### ISSUE THREAD

**Issue by yankay** [DaoCloud/DaoCloud-docs#70]
These Icon is good. 

We can add it after we certificated. like
(https://github.com/aws/eks-anywhere#amazon-eks-anywhere)](https://github.com/aws/eks-anywhere#amazon-eks-anywhere)

https://github.com/aws/eks-anywhere/pull/3026

**Comment by SAMZONG** [comment]
Great proposal. We'll be following up on that.
