### ISSUE TITLE
能否换个文档模板？

### ISSUE THREAD

**Issue by clark0x** [DaoCloud/daocloud-docs#9]
1. 左侧导航很难用，菜单会自动展开和滚动，跳来跳去，很难点到菜单
2. 正文区域的左右导航，总是打开新窗口，不能在当前页面打开么？
3. 搜索不好用，没反应，后来发现只是高亮了文本而且也不会跳到高亮的文本

**Comment by frankyuyong** [comment]
感谢您的反馈，目前的模版是我们暂时的一个过渡，近期会做比较完整的风格改变。目前使用的 Grav 简易模版，只是为了组织和编辑内容，稍后我们会另外开发模版，加强阅读体验。

**Comment by chenxizhang** [comment]
建议考虑gitbook，编排更加简单，而且可以生成pdf，epub等格式，便于分发。我自己就很希望能完整地下载这份文档，放在kindle上面阅读，呵呵。

**Comment by frankyuyong** [comment]
GitBook 我们试过，界面定制麻烦，而且管理工具不方便。

**Comment by fbigun** [comment]
想能在kindle上能看这个文档，希望有 epub格式

**Comment by SAMZONG** [comment]
迟来的回复，文档模板已更新完成。

**Comment by chenxizhang** [comment]
真的够迟的，Frank同学都离开道客好多年了

**Comment by SAMZONG** [comment]
> 真的够迟的，Frank 同学都离开道客好多年了

虽迟但到，期待在更好的舞台相遇。🤣🤣🤣
