### ISSUE TITLE
滚动屏幕时，上下页切换会随着滚动且盖在目录上

### ISSUE THREAD

**Issue by justedennnnn** [DaoCloud/DaoCloud-docs#91]
**Describe the bug**
滚动屏幕时，上下页切换会随着滚动且盖在目录上.

**Screenshots**
![image](https://user-images.githubusercontent.com/72536838/189283911-ee1cc240-ff3a-4c1e-bf78-65e52c85aa1d.png)

**Comment by justedennnnn** [comment]
偶现

**Comment by windsonsea** [comment]
@SAMZONG

**Comment by SAMZONG** [comment]
好的，我们来看看这个。

**Comment by windsonsea** [comment]
closed by PR #248
