### ISSUE TITLE
多云故障转移文档404

### ISSUE THREAD

**Issue by zgfh** [DaoCloud/DaoCloud-docs#974]
**Describe the bug**
如图：多云故障转移文档点击后显示404
<img width="591" alt="image" src="https://user-images.githubusercontent.com/11729624/221541820-88c90241-6121-469a-bb41-3d6f86145f31.png">

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by windsonsea** [comment]
Fixed now: https://docs.daocloud.io/kairship/failover/failover/

**Comment by windsonsea** [comment]
This issue is fixed, so close it now.
